name: Deployment

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

env:
  STACK_NAME: ${{ vars.STACK_NAME }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
  CERTIFICATE_ID: ${{ vars.CERTIFICATE_ID }}
  FORCE_COLOR: 3
  JSII_SILENCE_WARNING_UNTESTED_NODE_VERSION: 1

jobs:
  deploy:
    runs-on: ubuntu-22.04

    environment: production

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Keep npm cache around to speed up installs
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: build-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: github-action-rest-echo
          aws-region: ${{ vars.AWS_REGION }}

      - run: npx cdk diff

      - name: Deploy solution stack
        env:
          RELEASE_IMAGE_TAG: ${{ github.event.inputs.tag }}
        run: npx cdk deploy --require-approval never
